"""MOP 3231 · Lab #3 — Linear & Polynomial Regression.

Runs Steps 2–7 on data/cars_fuel_efficiency.csv, prints every number the lab
asks for, saves the plots to figures/ and writes the result tables plus the
written answers (Steps 4–7) to results.md. The answers are filled in from the
computed numbers, so after changing RANDOM_STATE a re-run updates everything.

    source .Imamsidikov_ML_lab_3/bin/activate
    python lab3.py
"""
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, cross_validate, train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

# Step 4: last 4 digits of my student ID.
# PLACEHOLDER — replace 1234 with the real digits and re-run the script.
RANDOM_STATE = 1234

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "cars_fuel_efficiency.csv"
FIG_DIR = ROOT / "figures"
RESULTS_PATH = ROOT / "results.md"

TARGET = "fuel_efficiency_km_per_l"
DEGREES = range(1, 6)

# In the written answers, a change in mean test R² smaller than this counts as
# "no real improvement" (Steps 5–7).
MIN_GAIN = 0.005

# The same shuffled 5-fold split is reused in Steps 4, 5 and 6 so their R² values
# are directly comparable. Shuffling matters: the CSV is ordered by model year.
CV = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 20)

report: list[str] = []  # markdown lines written to results.md at the end


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def section(title: str) -> None:
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")
    report.extend(["", f"## {title}", ""])


def md_table(header: list[str], rows: list[list[object]]) -> None:
    report.append("| " + " | ".join(header) + " |")
    report.append("|" + "---|" * len(header))
    for row in rows:
        report.append("| " + " | ".join(str(cell) for cell in row) + " |")
    report.append("")


def paragraph(*sentences: str) -> None:
    report.extend([" ".join(sentences), ""])


def code_list(names: list[str]) -> str:
    """Format names as `a`, `b` and `c` for the written answers."""
    quoted = [f"`{name}`" for name in names]
    if len(quoted) == 1:
        return quoted[0]
    return ", ".join(quoted[:-1]) + " and " + quoted[-1]


def regression_metrics(y_true: pd.Series, y_pred: np.ndarray) -> dict[str, float]:
    mse = mean_squared_error(y_true, y_pred)
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "MSE": mse,
        "RMSE": np.sqrt(mse),
        "R²": r2_score(y_true, y_pred),
    }


def cv_scores(model: BaseEstimator, X: pd.DataFrame, y: pd.Series) -> dict[str, np.ndarray]:
    """Per-fold train R², test R² and test RMSE on the shared 5-fold split."""
    scores = cross_validate(model, X, y, cv=CV, return_train_score=True,
                            scoring={"r2": "r2", "rmse": "neg_root_mean_squared_error"})
    return {
        "train_r2": scores["train_r2"],
        "test_r2": scores["test_r2"],
        "test_rmse": -scores["test_rmse"],
    }


def poly_model(degree: int) -> Pipeline:
    """Scale first, so high powers of the raw feature don't break least squares."""
    return make_pipeline(
        StandardScaler(),
        PolynomialFeatures(degree=degree, include_bias=False),
        LinearRegression(),
    )


FIG_DIR.mkdir(exist_ok=True)
report.append("# Lab #3 — results (generated by lab3.py)")
report.append("")
report.append(f"`random_state` = **{RANDOM_STATE}** (last 4 digits of student ID)")
if RANDOM_STATE == 1234:
    print("NOTE: RANDOM_STATE is still the placeholder 1234 — set it to your student ID digits.")
    report.append("")
    report.append("> **Placeholder.** Set `RANDOM_STATE` in `lab3.py` to the last 4 digits of "
                  "your student ID and re-run; every number and answer below will update.")

# ---------------------------------------------------------------------------
# Step 2 — Load and inspect the data
# ---------------------------------------------------------------------------
section("Step 2 — Load and inspect the data")

df = pd.read_csv(DATA_PATH)
print(df.shape)
print(df.dtypes)
print(df.describe())
print(df.isna().sum())

missing = df[df["power_hp"].isna()]
print("\nRows with missing power_hp:")
print(missing[["model", "year", "region"]])

rows_before = len(df)
df = df.dropna(subset=["power_hp"])
rows_dropped = rows_before - len(df)
share_dropped = f"{rows_dropped / rows_before:.2%}"
print(f"\nDropped {rows_dropped} of {rows_before} rows with missing power_hp "
      f"({share_dropped}); {len(df)} rows remain.")
md_table(
    ["Rows loaded", "Rows dropped (missing power_hp)", "Share dropped", "Rows used"],
    [[rows_before, rows_dropped, share_dropped, len(df)]],
)

# ---------------------------------------------------------------------------
# Step 3 — Simple linear regression
# ---------------------------------------------------------------------------
section("Step 3 — Simple linear regression")

corr = df.corr(numeric_only=True)[TARGET].drop(TARGET)
corr = corr.reindex(corr.abs().sort_values(ascending=False).index)
print("Correlation of each numeric feature with the target:")
print(corr.round(4))
md_table(["Feature", f"Correlation with `{TARGET}`"],
         [[f"`{name}`", f"{value:+.4f}"] for name, value in corr.items()])

numeric_features = list(corr.index)  # sorted by |correlation|, best first
best = numeric_features[0]
print(f"\nMost strongly correlated feature: {best} (r = {corr[best]:+.4f})")

X = df[[best]]
y = df[TARGET]

fig, ax = plt.subplots(figsize=(7, 5))
ax.scatter(X[best], y, s=14, alpha=0.6)
ax.set_xlabel(best)
ax.set_ylabel(TARGET)
ax.set_title(f"{TARGET} vs {best}")
fig.tight_layout()
fig.savefig(FIG_DIR / "step3_scatter.png", dpi=150)

model = LinearRegression()
model.fit(X, y)          # X: shape (n, 1); y: shape (n,)
print(model.intercept_, model.coef_)
theta0, theta1 = model.intercept_, model.coef_[0]
equation = f"y = {theta0:.4f} + ({theta1:.6f}) * x"

# Same figure again, now with the fitted line on top.
x_line = pd.DataFrame({best: np.linspace(X[best].min(), X[best].max(), 200)})
ax.plot(x_line[best], model.predict(x_line), color="tab:red", linewidth=2, label=equation)
ax.set_title(f"{TARGET} vs {best} with the fitted line")
ax.legend()
fig.savefig(FIG_DIR / "step3_fit.png", dpi=150)
plt.close(fig)

# The value to predict for: a round number near the middle of the feature's range.
median = X[best].median()
x_new = float(np.round(median, -1 if median >= 50 else 0))
y_new = model.predict(pd.DataFrame({best: [x_new]}))[0]
print(f"θ0 (intercept) = {theta0:.4f}")
print(f"θ1 (slope)     = {theta1:.6f}")
print(f"Fitted equation: {equation}")
print(f"Prediction for {best} = {x_new:g}: "
      f"y = {theta0:.4f} + ({theta1:.6f}) * {x_new:g} = {y_new:.2f} km/L")
md_table(["Feature", "θ0 (intercept)", "θ1 (slope)", "Example x", "Predicted y (km/L)"],
         [[f"`{best}`", f"{theta0:.4f}", f"{theta1:.6f}", f"{x_new:g}", f"{y_new:.2f}"]])
report.append(f"Fitted equation: `{equation}`")

# ---------------------------------------------------------------------------
# Step 4 — Evaluate the model honestly
# ---------------------------------------------------------------------------
section("Step 4 — Evaluate the model honestly")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE
)
n_train, n_test = len(X_train), len(X_test)
shared_rows = len(X_train.index.intersection(X_test.index))
split_model = LinearRegression().fit(X_train, y_train)
train_m = regression_metrics(y_train, split_model.predict(X_train))
test_m = regression_metrics(y_test, split_model.predict(X_test))

print(f"random_state = {RANDOM_STATE}; train rows = {n_train}, test rows = {n_test}, "
      f"rows in both = {shared_rows}")
print(f"{'Metric':<6}{'Train':>12}{'Test':>12}")
for name in train_m:
    print(f"{name:<6}{train_m[name]:>12.4f}{test_m[name]:>12.4f}")
md_table(["Metric", f"Train ({n_train} rows)", f"Test ({n_test} rows)"],
         [[name, f"{train_m[name]:.4f}", f"{test_m[name]:.4f}"] for name in train_m])

train_better = (train_m["R²"] > test_m["R²"]) and (train_m["RMSE"] < test_m["RMSE"])
print("Checkpoint: training metrics better than test metrics?", train_better)

simple_cv = cv_scores(LinearRegression(), X, y)
simple_folds = simple_cv["test_r2"]
simple_cv_mean, simple_cv_std = simple_folds.mean(), simple_folds.std()
simple_rmse = simple_cv["test_rmse"].mean()
print("\n5-fold CV test R² per fold:", np.round(simple_folds, 4))
print(f"Mean test R² = {simple_cv_mean:.4f}, std = {simple_cv_std:.4f}")
report.append(f"Checkpoint — train metrics better than test metrics: **{train_better}**")
report.append("")
md_table(["5-fold CV", *[f"Fold {i}" for i in range(1, 6)], "Mean", "Std"],
         [["Test R²", *[f"{s:.4f}" for s in simple_folds],
           f"{simple_cv_mean:.4f}", f"{simple_cv_std:.4f}"]])

if train_better:
    checkpoint_note = [
        f"Here train R² ({train_m['R²']:.4f}) is above test R² ({test_m['R²']:.4f}), as the "
        f"checkpoint expects, but only by {train_m['R²'] - test_m['R²']:.4f}.",
    ]
    luck = "the size of the gap mostly reflects"
else:
    checkpoint_note = [
        f"Here test R² ({test_m['R²']:.4f}) is actually above train R² ({train_m['R²']:.4f}).",
        f"That is not a leak: the model was fitted on the training rows only, and the two sets "
        f"share {shared_rows} rows.",
    ]
    luck = "which set scores higher mostly depends on"
checkpoint_note.append(f"A straight line has only two parameters and cannot memorise {n_train} "
                       f"cars, so {luck} which {n_test} cars landed in the test set.")
paragraph(
    "**Why the training score alone is not enough.**",
    "The training score is measured on the same cars the model used to choose θ0 and θ1, so it",
    "only shows how well the line fits data it has already seen; a flexible enough model could",
    "memorise the training cars, score perfectly on them and still fail on a new one.",
    "Only cars held out from fitting (the test set, or the held-out fold in cross-validation)",
    "show how the model does on a car it hasn't seen.",
    *checkpoint_note,
    f"This is why the 5-fold result (mean test R² {simple_cv_mean:.4f}, std {simple_cv_std:.4f}),",
    "which averages over five different splits, is the more reliable estimate.",
)

# ---------------------------------------------------------------------------
# Step 5 — Multiple linear regression
# ---------------------------------------------------------------------------
section("Step 5 — Multiple linear regression")

# One row per model: the k best-correlated features, for k = 1, 2, ...
step5_rows = []
for k in range(1, len(numeric_features) + 1):
    features = numeric_features[:k]
    scores = cv_scores(LinearRegression(), df[features], y)
    step5_rows.append({
        "features": features,
        "added": features[-1],
        "mean_r2": scores["test_r2"].mean(),
        "std_r2": scores["test_r2"].std(),
        "rmse": scores["test_rmse"].mean(),
    })
step5 = pd.DataFrame(step5_rows)
step5["change"] = step5["mean_r2"].diff()  # NaN for the first row

rows = []
for i, row in step5.iterrows():
    label = row.added if i == 0 else "+ " + row.added
    change_text = "—" if i == 0 else f"{row.change:+.4f}"
    rows.append([label, f"{row.mean_r2:.4f}", f"{row.std_r2:.4f}", change_text])
    print(f"{label:<22} mean test R² = {row.mean_r2:.4f} "
          f"(std {row.std_r2:.4f})  change = {change_text}")
md_table(["Features used (cumulative)", "Mean test R² (5-fold)", "Std", "Change vs previous row"],
         rows)

additions = step5.iloc[1:]
weak = additions[additions.change < MIN_GAIN]
top = additions.loc[additions.change.idxmax()]
top_rank = numeric_features.index(top.added) + 1
best_row = step5.mean_r2.idxmax()
all_r2 = step5.mean_r2.iloc[-1]
feature_corr = df[numeric_features].corr()

answer = ["**Did test R² improve every time a feature was added?**"]
if len(weak):
    answer.append(
        f"No. {len(weak)} of the {len(additions)} additions moved the mean test R² by less than "
        f"{MIN_GAIN}: " + ", ".join(f"`{r.added}` ({r.change:+.4f})" for r in weak.itertuples())
        + "."
    )
    lowered = list(weak.added[weak.change < 0])
    if lowered:
        answer.append(f"Adding {code_list(lowered)} actually lowered it.")
    # Explain each weak feature by the earlier feature it overlaps with most.
    for name in weak.added:
        earlier = numeric_features[:numeric_features.index(name)]
        partner = feature_corr.loc[name, earlier].abs().idxmax()
        answer.append(f"`{name}` overlaps with `{partner}` "
                      f"(r = {feature_corr.loc[name, partner]:+.2f}), which was already in the model.")
else:
    answer.append(f"Yes. Every addition raised the mean test R² by at least {MIN_GAIN}.")
top_sentence = f"The biggest gain came from `{top.added}` ({top.change:+.4f})"
if top_rank > 2:
    top_sentence += (f", even though it ranks only #{top_rank} of {len(numeric_features)} "
                     "by correlation with the target")
if top.added == "year":
    top_sentence += ("; it adds information (how new the car is) that the size and power "
                     "columns do not contain")
answer.append(top_sentence + ".")
if best_row < len(step5) - 1:
    answer.append(f"The model with every numeric feature scores {all_r2:.4f}, "
                  f"below the best row ({step5.mean_r2[best_row]:.4f}).")
answer.append(
    "So throwing every column into the model is not a free improvement: what a feature adds "
    "depends on what the model already contains, not on its own correlation with the target. "
    "A feature that repeats known information only gives least squares another coefficient to "
    "estimate from the same cars, so each addition has to earn its place on held-out data."
)
paragraph(*answer)

# ---------------------------------------------------------------------------
# Step 6 — Polynomial regression
# ---------------------------------------------------------------------------
section("Step 6 — Polynomial regression")

# One row per degree, indexed by the degree itself.
poly_rows = {}
for degree in DEGREES:
    scores = cv_scores(poly_model(degree), X, y)
    poly_rows[degree] = {"train_r2": scores["train_r2"].mean(),
                         "test_r2": scores["test_r2"].mean()}
poly = pd.DataFrame.from_dict(poly_rows, orient="index")
poly["change"] = poly["test_r2"].diff()

rows = []
for degree, row in poly.iterrows():
    change = "—" if degree == DEGREES[0] else f"{row.change:+.4f}"
    rows.append([degree, f"{row.train_r2:.4f}", f"{row.test_r2:.4f}", change])
    print(f"degree {degree}: train R² = {row.train_r2:.4f}, "
          f"test R² = {row.test_r2:.4f}, test change = {change}")
md_table(["Degree", "Train R² (5-fold mean)", "Test R² (5-fold mean)", "Test R² change"],
         rows)

first_degree, max_degree = DEGREES[0], DEGREES[-1]
best_degree = poly.test_r2.idxmax()
# The lowest degree whose test R² is within MIN_GAIN of the best one.
stop_degree = poly.index[poly.test_r2 >= poly.test_r2.max() - MIN_GAIN][0]
train_monotonic = bool((poly.train_r2.diff().dropna() >= -1e-12).all())
print(f"Highest mean test R² at degree {best_degree}")
print(f"Test R² stops improving (within {MIN_GAIN} of the best) at degree {stop_degree}")
print("Train R² never decreases with degree:", train_monotonic)
report.append(f"Highest mean test R²: degree **{best_degree}**")
report.append("")

fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(poly.index, poly.train_r2, marker="o", label="Train R² (5-fold mean)")
ax.plot(poly.index, poly.test_r2, marker="s", label="Test R² (5-fold mean)")
ax.set_xticks(poly.index)
ax.set_xlabel("Polynomial degree")
ax.set_ylabel("R²")
ax.set_title(f"Polynomial regression on {best}: R² vs degree")
ax.grid(alpha=0.3)
ax.legend()
fig.tight_layout()
fig.savefig(FIG_DIR / "step6_r2_vs_degree.png", dpi=150)
plt.close(fig)

later = poly.test_r2[poly.index > stop_degree]  # degrees past the stopping point
where = ["**Where test R² stops improving.**"]
if later.empty:
    where.append(f"Degree {max_degree} beats every lower degree by more than {MIN_GAIN}, so "
                 f"there is no clear stopping point within degrees 1–{max_degree} on this split.")
else:
    start_r2 = poly.test_r2[first_degree]
    if stop_degree == first_degree:
        rise = f"Test R² is {start_r2:.4f} at degree 1 and does not improve meaningfully after that"
    else:
        rise = (f"Test R² rises from {start_r2:.4f} at degree 1 to "
                f"{poly.test_r2[stop_degree]:.4f} at degree {stop_degree} and stops improving there")
    where.append(rise + f": no higher degree beats it by more than {MIN_GAIN} ("
                 + ", ".join(f"degree {d}: {r2:.4f}" for d, r2 in later.items()) + ").")
paragraph(*where)

why = [
    "**Why train R² keeps climbing while test R² does not.**",
    f"Train R² goes from {poly.train_r2[first_degree]:.4f} at degree 1 to "
    f"{poly.train_r2[max_degree]:.4f} at degree {max_degree}"
    + (" and never decreases." if train_monotonic else "."),
    "A higher-degree polynomial contains every lower-degree one (set the extra coefficients to "
    "zero), so on the cars it is fitted to it can only match or beat the lower degree.",
    "Each extra term is extra freedom to bend the curve toward the particular training cars, "
    "including their random scatter.",
]
if not later.empty:
    why.append(f"That scatter does not repeat in the held-out fold, so past degree {stop_degree} "
               "the extra bends buy nothing on test data, or lose a little.")
if stop_degree == 2:
    # Describe the curve from the signs of the fitted degree-2 coefficients.
    slope, curvature = poly_model(2).fit(X, y)[-1].coef_
    direction = "falls" if slope < 0 else "rises"
    bend = "flattens out" if slope * curvature < 0 else "gets steeper"
    why.append(f"Degree 2 already captures the real shape (fuel efficiency {direction} as "
               f"`{best}` grows, and the curve {bend} at high `{best}`), so the higher degrees "
               "only fit noise.")
low, high = X[best].min(), X[best].max()
why.append(f"This relies on standardizing `{best}` inside the pipeline first: its raw values span "
           f"{low:g}–{high:g}, so the degree-{max_degree} term would reach about "
           f"{high ** max_degree:.1e}, which makes plain least squares numerically unstable.")
paragraph(*why)

# ---------------------------------------------------------------------------
# Step 7 — Conclusion
# ---------------------------------------------------------------------------
section("Step 7 — Conclusion")

chosen = step5.features[best_row]
chosen_r2 = step5.mean_r2[best_row]
chosen_rmse = step5.rmse[best_row]
excluded = numeric_features[len(chosen):]
weak_kept = [name for name in weak.added if name in chosen]
best_poly_r2 = poly.test_r2.max()
year_min, year_max = df["year"].min(), df["year"].max()

if max(simple_cv_mean, best_poly_r2) >= chosen_r2:
    print("WARNING: a Step 3/6 model matches or beats the best Step 5 model; "
          "the generated conclusion does not fit these numbers — rewrite it by hand.")
    report.append("> **Warning.** The conclusion below assumes the Step 5 model is best, "
                  "which these numbers do not support. Rewrite it by hand.")
    report.append("")

choice = [
    f"I would use the multiple linear regression from Step 5 on {len(chosen)} features: "
    f"{code_list(chosen)}.",
    f"It has the highest mean 5-fold test R² of every model I fitted, {chosen_r2:.4f}, against "
    f"{simple_cv_mean:.4f} for simple regression on `{best}` and {best_poly_r2:.4f} for the best "
    f"polynomial (degree {best_degree}).",
    f"Its cross-validated RMSE is {chosen_rmse:.2f} km/L versus {simple_rmse:.2f} km/L for "
    f"`{best}` alone, so a typical prediction for a new car is off by about {chosen_rmse:.1f} km/L.",
]
if top.added in chosen:
    choice.append(f"Adding `{top.added}` was worth {top.change:+.4f} R², while bending the `{best}` "
                  f"line into a curve gained only {best_poly_r2 - simple_cv_mean:+.4f}.")
    if top.added == "year":
        choice.append(f"Cars became more efficient over the {year_min}–{year_max} model years even "
                      f"at the same `{best}`, and no curve in `{best}` alone can capture that.")
if excluded:
    choice.append(f"I left out {code_list(excluded)}: with every feature the mean test R² is "
                  f"{all_r2:.4f}, no better than this model, and each extra input is one more "
                  "thing to measure for a new car.")
if weak_kept:
    one = len(weak_kept) == 1
    choice.append(f"{code_list(weak_kept)} added less than {MIN_GAIN} R² when "
                  f"{'it' if one else 'they'} entered the model, so a leaner model without "
                  f"{'it' if one else 'them'} is worth testing next.")

caveats = [
    f"Only {rows_dropped} of {rows_before} rows ({share_dropped}) were dropped "
    f"for missing `power_hp`; they come from {missing['year'].nunique()} different model years "
    f"and {missing['region'].nunique()} regions, and so few rows cannot noticeably move "
    f"coefficients fitted on the remaining {len(df)} cars.",
    f"One caution: the model only saw cars from {year_min}–{year_max}, so "
    + ("its `year` effect should not be extrapolated to modern cars."
       if "year" in chosen else "it should not be trusted for modern cars."),
]
paragraph(*choice)
paragraph(*caveats)

word_count = len(" ".join(choice + caveats).split())
report.append(f"_Word count: {word_count}_")
print(f"Chosen model: multiple linear regression on {', '.join(chosen)}")
print(f"Mean test R² = {chosen_r2:.4f}, CV RMSE = {chosen_rmse:.2f} km/L")
print(f"Conclusion word count: {word_count}"
      + ("" if 150 <= word_count <= 250 else "  WARNING: the lab asks for 150–250 words"))

RESULTS_PATH.write_text("\n".join(report) + "\n", encoding="utf-8")
print(f"\nSaved figures to {FIG_DIR.name}/ and tables + written answers to {RESULTS_PATH.name}")
