"""MOP 3231 · Lab #3 — Linear & Polynomial Regression.

Runs Steps 2–7 on data/cars_fuel_efficiency.csv, prints every number the lab
asks for, saves the plots to figures/ and writes the result tables plus the
written answers (Steps 4–7) to results.md. The answers are filled in from the
computed numbers, so after changing RANDOM_STATE (lab/config.py) a re-run
updates everything.

    source .Imamsidikov_ML_lab_3/bin/activate
    python lab3.py

Each step lives in its own module under lab/:

    config.py            seed, paths, shared 5-fold split
    report.py            builds results.md
    modeling.py          metrics, cross-validation, polynomial pipeline
    plots.py             the three figures
    step2_data.py ... step7_conclusion.py   one file per lab step
"""
import pandas as pd

from lab import (step2_data, step3_simple, step4_evaluate, step5_multiple,
                 step6_polynomial, step7_conclusion)
from lab.config import FIG_DIR, PLACEHOLDER_STATE, RANDOM_STATE, RESULTS_PATH
from lab.report import Report


def main() -> None:
    pd.set_option("display.width", 120)
    pd.set_option("display.max_columns", 20)
    FIG_DIR.mkdir(exist_ok=True)

    report = Report()
    report.add("# Lab #3 — results (generated by lab3.py)", "",
               f"`random_state` = **{RANDOM_STATE}** (last 4 digits of student ID)")
    if RANDOM_STATE == PLACEHOLDER_STATE:
        print("NOTE: RANDOM_STATE is still the placeholder 1234 — set it to your student ID digits.")
        report.add("", "> **Placeholder.** Set `RANDOM_STATE` in `lab/config.py` to the last 4 "
                   "digits of your student ID and re-run; every number and answer below will "
                   "update.")

    # Each step prints its numbers, adds its part of results.md and returns what later
    # steps need.
    data = step2_data.run(report)
    fit = step3_simple.run(report, data.df)
    simple = step4_evaluate.run(report, fit)
    search = step5_multiple.run(report, data.df, fit)
    poly = step6_polynomial.run(report, fit)
    step7_conclusion.run(report, data, fit, simple, search, poly)

    report.save(RESULTS_PATH)
    print(f"\nSaved figures to {FIG_DIR.name}/ and tables + written answers to "
          f"{RESULTS_PATH.name}")


if __name__ == "__main__":
    main()
