"""MOP 3231 · Lab #3 — Linear & Polynomial Regression.

Runs Steps 2–6 on data/cars_fuel_efficiency.csv, prints every number the lab
asks for, saves the plots to figures/ and the result tables to results.md.

    source .Imamsidikov_ML_lab_3/bin/activate
    python lab3.py
"""
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import KFold, cross_validate, train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

# Step 4: last 4 digits of my student ID.
# PLACEHOLDER — replace 1234 with the real digits and re-run the script.
RANDOM_STATE = 1234

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "cars_fuel_efficiency.csv"
FIG_DIR = ROOT / "figures"
RESULTS_PATH = ROOT / "results.md"

TARGET = "fuel_efficiency_km_per_l"
DEGREES = range(1, 6)

# The same shuffled 5-fold split is reused in Steps 4, 5 and 6 so their R² values
# are directly comparable. Shuffling matters: the CSV is ordered by model year.
CV = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 20)

report = []  # markdown lines written to results.md at the end


def section(title):
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")
    report.extend(["", f"## {title}", ""])


def md_table(header, rows):
    report.append("| " + " | ".join(header) + " |")
    report.append("|" + "---|" * len(header))
    for row in rows:
        report.append("| " + " | ".join(str(cell) for cell in row) + " |")
    report.append("")


def regression_metrics(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    return {
        "MAE": mean_absolute_error(y_true, y_pred),
        "MSE": mse,
        "RMSE": np.sqrt(mse),
        "R²": r2_score(y_true, y_pred),
    }


def cv_r2(model, X, y):
    """Return (train R² per fold, test R² per fold) for 5-fold CV."""
    scores = cross_validate(model, X, y, cv=CV, scoring="r2", return_train_score=True)
    return scores["train_score"], scores["test_score"]


FIG_DIR.mkdir(exist_ok=True)
report.append("# Lab #3 — results (generated by lab3.py)")
report.append("")
report.append(f"`random_state` = **{RANDOM_STATE}** (last 4 digits of student ID)")

# ---------------------------------------------------------------------------
# Step 2 — Load and inspect the data
# ---------------------------------------------------------------------------
section("Step 2 — Load and inspect the data")

df = pd.read_csv(DATA_PATH)
print(df.shape)
print(df.dtypes)
print(df.describe())
print(df.isna().sum())

rows_before = len(df)
df = df.dropna(subset=["power_hp"])
rows_dropped = rows_before - len(df)
print(f"\nDropped {rows_dropped} of {rows_before} rows with missing power_hp "
      f"({rows_dropped / rows_before:.2%}); {len(df)} rows remain.")
md_table(
    ["Rows loaded", "Rows dropped (missing power_hp)", "Share dropped", "Rows used"],
    [[rows_before, rows_dropped, f"{rows_dropped / rows_before:.2%}", len(df)]],
)

# ---------------------------------------------------------------------------
# Step 3 — Simple linear regression
# ---------------------------------------------------------------------------
section("Step 3 — Simple linear regression")

corr = df.corr(numeric_only=True)[TARGET].drop(TARGET)
corr = corr.reindex(corr.abs().sort_values(ascending=False).index)
print("Correlation of each numeric feature with the target:")
print(corr.round(4))
md_table(["Feature", f"Correlation with `{TARGET}`"],
         [[f"`{name}`", f"{value:+.4f}"] for name, value in corr.items()])

best = corr.index[0]
numeric_features = list(corr.index)  # sorted by |correlation|, best first
print(f"\nMost strongly correlated feature: {best} (r = {corr[best]:+.4f})")

X = df[[best]]
y = df[TARGET]

fig, ax = plt.subplots(figsize=(7, 5))
ax.scatter(X[best], y, s=14, alpha=0.6)
ax.set_xlabel(best)
ax.set_ylabel(TARGET)
ax.set_title(f"{TARGET} vs {best}")
fig.tight_layout()
fig.savefig(FIG_DIR / "step3_scatter.png", dpi=150)

model = LinearRegression()
model.fit(X, y)          # X: shape (n, 1); y: shape (n,)
print(model.intercept_, model.coef_)
theta0, theta1 = model.intercept_, model.coef_[0]

x_line = pd.DataFrame({best: np.linspace(X[best].min(), X[best].max(), 200)})
ax.plot(x_line[best], model.predict(x_line), color="tab:red", linewidth=2,
        label=f"y = {theta0:.4f} + ({theta1:.6f}) * x")
ax.set_title(f"{TARGET} vs {best} with the fitted line")
ax.legend()
fig.savefig(FIG_DIR / "step3_fit.png", dpi=150)
plt.close(fig)

# The value to predict for: a round number near the middle of the feature's range.
x_new = float(np.round(X[best].median(), -1 if X[best].median() >= 50 else 0))
y_new = model.predict(pd.DataFrame({best: [x_new]}))[0]
print(f"θ0 (intercept) = {theta0:.4f}")
print(f"θ1 (slope)     = {theta1:.6f}")
print(f"Fitted equation: y = {theta0:.4f} + ({theta1:.6f}) * x")
print(f"Prediction for {best} = {x_new:g}: "
      f"y = {theta0:.4f} + ({theta1:.6f}) * {x_new:g} = {y_new:.2f} km/L")
md_table(["Feature", "θ0 (intercept)", "θ1 (slope)", "Example x", "Predicted y (km/L)"],
         [[f"`{best}`", f"{theta0:.4f}", f"{theta1:.6f}", f"{x_new:g}", f"{y_new:.2f}"]])
report.append(f"Fitted equation: `y = {theta0:.4f} + ({theta1:.6f}) * x`")

# ---------------------------------------------------------------------------
# Step 4 — Evaluate the model honestly
# ---------------------------------------------------------------------------
section("Step 4 — Evaluate the model honestly")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE
)
split_model = LinearRegression().fit(X_train, y_train)
train_m = regression_metrics(y_train, split_model.predict(X_train))
test_m = regression_metrics(y_test, split_model.predict(X_test))

print(f"random_state = {RANDOM_STATE}; train rows = {len(X_train)}, test rows = {len(X_test)}")
print(f"{'Metric':<6}{'Train':>12}{'Test':>12}")
for name in train_m:
    print(f"{name:<6}{train_m[name]:>12.4f}{test_m[name]:>12.4f}")
md_table(["Metric", f"Train ({len(X_train)} rows)", f"Test ({len(X_test)} rows)"],
         [[name, f"{train_m[name]:.4f}", f"{test_m[name]:.4f}"] for name in train_m])

train_better = (train_m["R²"] > test_m["R²"]) and (train_m["RMSE"] < test_m["RMSE"])
print("Checkpoint: training metrics better than test metrics?", train_better)

train_folds, test_folds = cv_r2(LinearRegression(), X, y)
print("\n5-fold CV test R² per fold:", np.round(test_folds, 4))
print(f"Mean test R² = {test_folds.mean():.4f}, std = {test_folds.std():.4f}")
report.append(f"Checkpoint — train metrics better than test metrics: **{train_better}**")
report.append("")
md_table(["5-fold CV", *[f"Fold {i}" for i in range(1, 6)], "Mean", "Std"],
         [["Test R²", *[f"{s:.4f}" for s in test_folds],
           f"{test_folds.mean():.4f}", f"{test_folds.std():.4f}"]])

# ---------------------------------------------------------------------------
# Step 5 — Multiple linear regression
# ---------------------------------------------------------------------------
section("Step 5 — Multiple linear regression")

rows = []
previous = None
for k in range(1, len(numeric_features) + 1):
    features = numeric_features[:k]
    _, test_folds = cv_r2(LinearRegression(), df[features], y)
    mean_r2 = test_folds.mean()
    label = features[0] if k == 1 else "+ " + features[-1]
    change = "—" if previous is None else f"{mean_r2 - previous:+.4f}"
    rows.append([label, f"{mean_r2:.4f}", f"{test_folds.std():.4f}", change])
    print(f"{label:<22} mean test R² = {mean_r2:.4f} "
          f"(std {test_folds.std():.4f})  change = {change}")
    previous = mean_r2
md_table(["Features used (cumulative)", "Mean test R² (5-fold)", "Std", "Change vs previous row"],
         rows)

# ---------------------------------------------------------------------------
# Step 6 — Polynomial regression
# ---------------------------------------------------------------------------
section("Step 6 — Polynomial regression")

train_r2, test_r2 = [], []
for degree in DEGREES:
    pipe = make_pipeline(
        StandardScaler(),
        PolynomialFeatures(degree=degree, include_bias=False),
        LinearRegression(),
    )
    train_folds, test_folds = cv_r2(pipe, X, y)
    train_r2.append(train_folds.mean())
    test_r2.append(test_folds.mean())

rows = []
for i, degree in enumerate(DEGREES):
    change = "—" if i == 0 else f"{test_r2[i] - test_r2[i - 1]:+.4f}"
    rows.append([degree, f"{train_r2[i]:.4f}", f"{test_r2[i]:.4f}", change])
    print(f"degree {degree}: train R² = {train_r2[i]:.4f}, "
          f"test R² = {test_r2[i]:.4f}, test change = {change}")
md_table(["Degree", "Train R² (5-fold mean)", "Test R² (5-fold mean)", "Test R² change"],
         rows)

best_degree = list(DEGREES)[int(np.argmax(test_r2))]
print(f"Highest mean test R² at degree {best_degree}")
print("Train R² never decreases with degree:", bool(np.all(np.diff(train_r2) >= -1e-12)))
report.append(f"Highest mean test R²: degree **{best_degree}**")

fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(list(DEGREES), train_r2, marker="o", label="Train R² (5-fold mean)")
ax.plot(list(DEGREES), test_r2, marker="s", label="Test R² (5-fold mean)")
ax.set_xticks(list(DEGREES))
ax.set_xlabel("Polynomial degree")
ax.set_ylabel("R²")
ax.set_title(f"Polynomial regression on {best}: R² vs degree")
ax.grid(alpha=0.3)
ax.legend()
fig.tight_layout()
fig.savefig(FIG_DIR / "step6_r2_vs_degree.png", dpi=150)
plt.close(fig)

RESULTS_PATH.write_text("\n".join(report) + "\n", encoding="utf-8")
print(f"\nSaved figures to {FIG_DIR.name}/ and tables to {RESULTS_PATH.name}")
